### ISSUE TITLE
Emote animations support

### ISSUE THREAD

**Issue by modulesio** [exokitxr/avatars#23]
Exokit Avatars loads `.unitypackage` files, but the animations seem separate from the actual FBX models.

If we want emotes, I think we'd need to parse the `.anim` YAML files in the pacakges and inject them into the THREE.js animation system, which should be able to handle the mixing. The YAML files look like this:

```
%YAML 1.1
%TAG !u! tag:unity3d.com,2011:
--- !u!74 &7400000
AnimationClip:
  m_ObjectHideFlags: 0
  m_PrefabParentObject: {fileID: 0}
  m_PrefabInternal: {fileID: 0}
  m_Name: Dab
  serializedVersion: 6
  m_Legacy: 0
  m_Compressed: 0
  m_UseHighQualityCurve: 0
  m_RotationCurves: []
  m_CompressedRotationCurves: []
  m_EulerCurves: []
  m_PositionCurves: []
  m_ScaleCurves: []
  m_FloatCurves:
  - curve:
      serializedVersion: 2
      m_Curve:
      - serializedVersion: 2
        time: 0
        value: -0.012714
        inSlope: 0.17463881
        outSlope: 0.17463881
        tangentMode: 0
      - serializedVersion: 2
        time: 0.033333335
        value: -0.0068927067
        inSlope: 0.25062943
        outSlope: 0.25062943
        tangentMode: 0
```
